language: java

jdk:
  - oraclejdk8

script:
  - ./gradlew ":$MODULE:build" ":$MODULE:uploadArchives"

env:
   matrix:
     - MODULE=json-aws
     - MODULE=json-core
     - MODULE=json-generator
     - MODULE=json-ld
     - MODULE=json-schema
     - MODULE=json-wrapper
     - MODULE=model-generator


notifications:
  email: true

sudo: false

cache:
   directories:
        - $HOME/.gradle