language: java

jdk:
  - oraclejdk8

install: echo "skip 'gradle assemble' step"

script:
  - ./gradlew ":$MODULE:build"

after_success:
  - .buildscript/deploy_snapshot.sh

env:
   matrix:
     - MODULE=json-aws
     - MODULE=json-core
     - MODULE=json-generator
     - MODULE=json-ld
     - MODULE=json-schema
     - MODULE=json-wrapper
     - MODULE=model-generator


notifications:
  email: true

sudo: false

cache:
   directories:
        - $HOME/.gradle